services:
  remote-controller:
    build: .
    ports:
      - "8000:8000"
    environment:
      ADAM_FRAME_API: "https://frame-adam.maggisnorra.is/api"
      STEVE_FRAME_API: "https://frame-steve.maggisnorra.is/api"
    restart: unless-stopped
